apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jar-0
spec:
  capacity:
    storage: 5Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadOnlyMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below 
  storageClassName: "nfs-jar"
  nfs:
    server: double-dutch.ca # Please change this to your NFS server
    path: /public # Please change this to the relevant share
    readOnly: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jar-1
spec:
  capacity:
    storage: 5Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadOnlyMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below 
  storageClassName: "nfs-jar"
  nfs:
    server: double-dutch.ca # Please change this to your NFS server
    path: /public # Please change this to the relevant share
    readOnly: true