apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-jar-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "nfs-jar"
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: "/nfsshare"
        name: nfs-jar-volume
  volumes:
    - name: nfs-jar-volume
      persistentVolumeClaim:
        claimName: nfs-jar-claim
