version: "3"
services:
  nfs-server-alpine:
    privileged: true
    container_name: nfs
    volumes:
      - '/tmp:/nfsshare'
    environment:
      - SHARED_DIRECTORY=/nfsshare
      - READ_ONLY=true
    image: 'itsthenetwork/nfs-server-alpine:12'
    ports:
      - '2049:2049'
      # - '2049:2049/udp'
      # - '111:111'
      # - '111:111/udp'
      # - '32765:32765'
      # - '32765:32765/udp'
      # - '32767:32767'
      # - '32767:32767/udp'
