apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: "/nfsshare"
        name: nfs-jar-volume
  volumes:
    - name: nfs-jar-volume
      nfs:
        path: /public
        server: double-dutch.ca
        readOnly: true
---
# Create a second pod to demonstrate multiple pods can bind to the same nfs volume using the nfs volume plugin
apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: "/nfsshare"
        name: nfs-jar-volume
  volumes:
    - name: nfs-jar-volume
      nfs:
        path: /public
        server: double-dutch.ca
        readOnly: true
